### ISSUE TITLE
Invalid multibyte string in test data

### ISSUE THREAD

**Issue by kcranston** [AlejandroRuete/IgnoranceMaps#1]
Trying to run the application, following the instructions at http://alejandroruete.github.io/IgnoranceMaps/, I get the following error:

```
> require(shiny)
Loading required package: shiny
> runApp("/Users/karen/Desktop/AlejandroRuete-IgnoranceMaps-7850e22/SLWapp")

Listening on http://127.0.0.1:5921
Warning in is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
Error in writeChar(text, conn, eos = NULL) : 
  invalid multibyte string at '<93>int<65>resting<94> species are (in Sweden, a moose is not as frequently reported as
hedgehogs are). Therefore, one can expect that for common species the observations
are very scattered and they do not cover the whole expected range of the
species.</p>

<p class=MsoNormal><b style='mso-bidi-font-weight:normal'>Tabs (Maps, Data
plots, and Read me)<o:p></o:p></b></p>

<p class=MsoNormal>You are now reading under the <93>Read me<94> tab. The data is
shown the form of <93>Maps<94> and <93>Data plots<94>. Four maps of Sweden with a
resolution of 10 x 10 km are plotted under the tab <93>Maps<94> displaying: </p>

<p class=MsoListParagraphCxSpFirst style='text-indent:-18.0pt;mso-list:l1 level1 lfo2'><![if !supportLists]><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'><span
style='mso-list:Ignore'>1)<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>the number of ob
```

R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin10.8.0 (64-bit)
shiny 0.10.1 0.11.1

**Comment by aleruete** [comment]
Dear kcraston,
it seems the problem you mention showed up when reading under the "Read Me" Tab. Is that right?
In that case, there must be a compatibility problem on the text file behind that file. Are you using MAC?
If you can view the other tabs correctly, please refer to the .docx file stored in the "data" folder for the explanatory text while I check this issue. If you can't open anything, please comment out (using #) the lines 102 and 103 on the ui.r file 
(e.g. # tabPanel("Read me", includeHTML("data/Description.htm")
        # )# end tab Read me,). 

Regards, 

Alejandro

**Comment by kcranston** [comment]
I am getting that error message in Rstudio and also in the browser immediately after running `runApp("/Users/karen/Desktop/AlejandroRuete-IgnoranceMaps-7850e22/SLWapp")`. The application never starts, so I can't view any tabs. If I comment out lines 102 and 102 in ui.R, the shiny window opens with the error message `ERROR: argument is missing, with no default`

I am running on Max OS X 10.10 (Yosemite).

**Comment by aleruete** [comment]
Hi,
I am sorry, you should also comment out the last comma in line 101. Working
on the full solution.

[image: Alejandro Ruete on about.me]

Alejandro Ruete
about.me/alejandro.ruete
  http://about.me/alejandro.ruete

2015-02-25 20:13 GMT+01:00 Karen Cranston notifications@github.com:

**Comment by aleruete** [comment]
Dear Karen,
would you please test the new version? I updated particularly the
"data/description.htm" file, where I think there was a compatibility
problem.
Let me know if it still doesn't run properly.
Kind regards,

Alejandro

[image: Alejandro Ruete on about.me]

Alejandro Ruete
about.me/alejandro.ruete
  http://about.me/alejandro.ruete

2015-02-26 1:38 GMT+01:00 Alejandro Ruete aleruete@gmail.com:

**Comment by kcranston** [comment]
If I leave ui.R unchanged, I still get the same error as in my first post. If I comment out the Read me tab panel (including the comma in the previous line) it works. I do get the following warning, though:

```
> runApp("/Users/karen/Desktop/IgnoranceMaps/SLWapp")

Listening on http://127.0.0.1:5995
Warning in is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
```

**Comment by aleruete** [comment]
Dear Karen,
did you downloaded the last version of the application from GitHub? In that
case, could you make two more tests for me? As far as I know you are the
only Mac user that has tested the app.

I attached a new Description.htm file. First, could you check if you can
open it correctly by dragging and dropping it into your internet browser?
If you cannot open it, then the problem is somewhere in your browser,
triggering an error in the shinny application.
Second, can you replace the file data/Description.htm from the downloaded
application with the file I attached in this email?

The warning you get when running the app (Warning in is.na(x) :...) is
trivial, and I will get rid of it on the next update.

Thank you for your feed back! it makes me progress.

Alejandro

[image: Alejandro Ruete on about.me]

Alejandro Ruete
about.me/alejandro.ruete
  http://about.me/alejandro.ruete

2015-02-25 22:30 GMT-03:00 Karen Cranston notifications@github.com:

**Comment by aleruete** [comment]
Dear Karen, 
could you please test the latest version of this app?
You should now be able to see the  "read me" tab. 

Please use this script that should be easier to run: 

   require(shiny)
   shiny::runGitHub(repo="IgnoranceMaps", username="alejandroruete", subdir="SLWapp")

Thank you very much.
